############################################################
#               Include SharedLibraries                    #
############################################################
# Include all SharedLibraries
include:
  - local: '/scripts/variables.yml'
  - project: "energi/tech/devops/gitlab-ci-shared-jobs"
    ref: "develop"
    file:
      - "libs/gitlab/cd/templates/jobs/kube/k8s-jobs.yml"
############################################################
#                      Variables                           #
############################################################
# Include all variables
variables:
  PROJECT: "energi"
  CLUSTERNAME: $PROJECT-$ENV-eks-cluster
  APP_PROJECT: "energi"
  APP_NAME: "explorer"
  HELM_CHART_PATH: "./helm"
  REPOSITORY_NAME_WEBAPP: "energi/explorer/webapp"
  REPOSITORY_NAME_INDEXER: "energi/explorer/indexer"
  NAMESPACE: ${APP_PROJECT}-${APP_NAME}-${APP_ENV}
  HELM_CHART: ${APP_PROJECT}-${APP_NAME}-${APP_ENV}
  AWS_ECR: 769325152790.dkr.ecr.us-west-2.amazonaws.com
  AWS_REGION: "us-west-2"
############################################################
#                         Stages                           #
############################################################
stages:
  - build-base
  - build-dev-image
  - checks
  - build
  - scan
  - deploy
############################################################
#                       Triggers                           #
############################################################
    
.testnet_triggers: &testnet_triggers
  refs:
    - develop

.mainnet_triggers: &mainnet_triggers
  refs:
    - master

############################################################
#                        Runner                            #
############################################################
.runner:
  tags: [docker_runner]

############################################################
#                     Build Base Image                     #
############################################################
build-base:
  stage: build-base
  tags:
    - docker_runner
  before_script:
    - apk add bash
  script:
    - cd scripts
    - ./start.sh -r build_base_image
    - docker tag $BASE_IMAGE_LATEST $BASE_IMAGE_COMMIT
    - docker push $BASE_IMAGE_COMMIT
    - docker push $BASE_IMAGE_LATEST
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .tool-versions
        - scripts/build_base_image

############################################################
#                  Build Developer Image                   #
############################################################
build-dev-image:
  stage: build-dev-image
  tags:
    - docker_runner
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cp submodules/src/assets/* apps/block_scout_web/assets/static/images/tokens
    - cd scripts
    - sed -i "s|$DEFAULT_IMAGE|$BASE_IMAGE_LATEST|g" Dockerfile_webapp
    - docker build --cache-from $TAG2_LATEST -f ./Dockerfile_webapp -t $TAG2_COMMIT ../
    - docker push $TAG2_COMMIT
    - echo "########################################################################"
    - echo " Run to pull image"
    - echo " docker pull $ECR_PROXY_REGISTRY/$APP2_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "########################################################################"
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "false" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - submodules/src/assets/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
      when: manual

############################################################
#                Check Vuln and configs                    #
############################################################
check-explorer:
  stage: checks
  needs: [build-base]
  tags:
    - docker_runner
  image:
    name: aquasec/trivy:latest
    entrypoint: ['']
  services:
    - docker:dind
  script:
    - echo "Scan $APP_NAME Docker Image for the $ENVIRONMENT"
    - trivy fs --severity CRITICAL,HIGH --security-checks vuln,config .
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  allow_failure: true
  retry:
    max: 2
    when:
      - script_failure
      - runner_system_failure
      - stuck_or_timeout_failure  
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
    - if: $CI_COMMIT_TAG

############################################################
#                      Build indexer                       #
############################################################
build-indexer:
  stage: build
  needs: [build-base,check-explorer]
  tags:
    - docker_runner
  script:
    - cd scripts
    - sed -i "s|$DEFAULT_IMAGE|$BASE_IMAGE_LATEST|g" Dockerfile_indexer
    - docker build --cache-from $TAG1_LATEST -f ./Dockerfile_indexer -t $TAG1_COMMIT -t $TAG1_LATEST -t ${AWS_ECR}/${REPOSITORY_NAME_INDEXER}:${CI_COMMIT_SHORT_SHA} ../
    - docker push $TAG1_COMMIT
    - docker push $TAG1_LATEST
    - docker push ${AWS_ECR}/${REPOSITORY_NAME_INDEXER}:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
    - if: $CI_COMMIT_TAG

############################################################
#                       Build webapp                       #
############################################################
build-webapp:
  stage: build
  needs: [build-base,check-explorer]
  tags:
    - docker_runner
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cp submodules/src/assets/* apps/block_scout_web/assets/static/images/tokens
    - cd scripts
    - sed -i "s|$DEFAULT_IMAGE|$BASE_IMAGE_LATEST|g" Dockerfile_webapp
    - docker build --cache-from $TAG2_LATEST -f ./Dockerfile_webapp -t $TAG2_COMMIT -t $TAG2_LATEST -t ${AWS_ECR}/${REPOSITORY_NAME_WEBAPP}:${CI_COMMIT_SHORT_SHA} ../
    - docker push $TAG2_COMMIT
    - docker push $TAG2_LATEST
    - docker push ${AWS_ECR}/${REPOSITORY_NAME_WEBAPP}:${CI_COMMIT_SHORT_SHA}

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - submodules/src/assets/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
    - if: $CI_COMMIT_TAG

############################################################
#                       Scan webapp                       #
############################################################
scan-webapp:
  stage: scan
  needs: [build-webapp]
  tags:
    - docker_runner
  image:
    name: aquasec/trivy:latest
    entrypoint: ['']
  services:
    - docker:dind
  script:
    - echo "Scan $APP_NAME Docker Image for the $ENVIRONMENT"
    - trivy image --exit-code 1 --no-progress --severity CRITICAL $CONTAINER_REGISTRY/$APP2_NAME:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  allow_failure: true
  retry:
    max: 2
    when:
      - script_failure
      - runner_system_failure
      - stuck_or_timeout_failure  
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
    - if: $CI_COMMIT_TAG

############################################################
#                       Scan indexer                       #
############################################################
scan-indexer:
  stage: scan
  needs: [build-indexer]
  tags:
    - docker_runner
  image:
    name: aquasec/trivy:latest
    entrypoint: ['']
  services:
    - docker:dind
  script:
    - echo "Scan $APP_NAME Docker Image for the $ENVIRONMENT"
    - trivy image --exit-code 1 --no-progress --severity CRITICAL $CONTAINER_REGISTRY/$APP1_NAME:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  allow_failure: true
  retry:
    max: 2
    when:
      - script_failure
      - runner_system_failure
      - stuck_or_timeout_failure 
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - .gitlab-ci.yml
        - apps/**/*
        - scripts/Dockerfile_{indexer,webapp,base_image}
        - scripts/start.sh
    - if: $CI_COMMIT_TAG

############################################################
#                        Testnet                           #
############################################################

# Deploy Explorer in Testnet
helm deploy testnet:
  stage: deploy
  needs: [scan-indexer,scan-webapp]
  variables:
    ENV: "dev"
    APP_ENV: "testnet"
    ENVSUBST: "true"
    ACCOUNT: "769325152790"
    APP_DNS: "explorer.test.energi.network"
    CERTIFICATE_ARN: "arn:aws:acm:us-west-2:769325152790:certificate/1d7ee6f5-2c79-4afc-adbb-63dfa9e14080"
  tags: [docker_runner]
  extends: .helm_charts_deploy
  only:
    <<: *testnet_triggers 

############################################################
#                        Mainnet                           #
############################################################

# Deploy Explorer in Mainnet
helm deploy mainnet:
  stage: deploy
  needs: [scan-indexer,scan-webapp]
  variables:
    ENV: "mainnet"
    APP_ENV: "mainnet"
    ENVSUBST: "true"
    ACCOUNT: "930210061793"
    ROLE_NAME: "energi-automation"
    ROLE_ARN: "arn:aws:iam::930210061793:role/energi-automation"
    APP_DNS: "explorer.energi.network"
    CERTIFICATE_ARN: "arn:aws:acm:us-west-2:930210061793:certificate/be0e042a-10b7-4d8d-b432-a8b3622c30ee"
  tags: [docker_runner]
  extends: .helm_charts_deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  only:
    <<: *mainnet_triggers 
