variables:
  SERVER_USER: ubuntu
  SCHEMA_NAME: explorer_schema
  SBX_SERVER_IP: $SANDBOX_SERVER_IP
  SBX_SERVER_HOST: explorer.develop.energi.network
  TESTNET_SERVER_HOST: explorer.test.energi.network
  MAINNET_SERVER_HOST: explorer.energi.network
  APP_DIR: /home/$SERVER_USER
  APP1_NAME: explorer_webapp
  APP2_NAME: explorer_indexer
  TAG1_LATEST: $CONTAINER_REGISTRY/$APP1_NAME:latest
  TAG1_COMMIT: $CONTAINER_REGISTRY/$APP1_NAME:$CI_COMMIT_SHORT_SHA
  TAG2_LATEST: $CONTAINER_REGISTRY/$APP2_NAME:latest
  TAG2_COMMIT: $CONTAINER_REGISTRY/$APP2_NAME:$CI_COMMIT_SHORT_SHA
  PROJECT_NAME: BlockExplorer

stages:
  - build
  - deploy-sbx-schema
  - deploy-sbx
  - deploy-testnet-schema
  - deploy-testnet-indexer
  - deploy-testnet-webapp
  - deploy-mainnet-schema
  - deploy-mainnet-indexer
  - deploy-mainnet-webapp

.sbx_triggers: &sbx_triggers
  refs:
    - sandbox

.testnet_triggers: &testnet_triggers
  refs:
    - develop

.mainnet_triggers: &mainnet_triggers
  refs:
    - master

.runner:
  tags: [docker_runner]

.before_script_template: &testnet_indexer_vars
  before_script:
    - cd scripts
    - sed -i "12iIMAGE=$CONTAINER_REGISTRY" start.sh
    - cp template.env testnet.env
    - sed -i "s/CORENODEIP/${TESTNET_CORENODE_IP1}/g" testnet.env
    - sed -i "s/WSPORT/49795/g" testnet.env
    - sed -i "s/HTTPPORT/49796/g" testnet.env
    - sed -i "s/CHAINID/49797/g" testnet.env
    - sed -i "s|SECRETKEYBASE|${TESTNET_SECRET_KEY_BASE}|g" testnet.env
    - sed -i "s/DBUSERNAME/${TESTNET_DB_USERNAME}/g" testnet.env
    - sed -i "s|DBPASSWORD|${TESTNET_DB_PASSWORD}|g" testnet.env
    - sed -i "s/DBNAME/${TESTNET_DB_NAME}/g" testnet.env
    - sed -i "s/DBHOST/${TESTNET_DB_HOSTNAME}/g" testnet.env
    - sed -i "s/REWARDS_CONTRACT/\#REWARDS_CONTRACT/g" testnet.env
    #- sed -i "s/REWARDCONTRACT/${TESTNET_REWARDCONTRACT}/g" testnet.env
    - sed -i "s/EXPLORERHOST/${TESTNET_SERVER_HOST}/g" testnet.env
    - sed -i "s/CAPTCHASECRET/${CAPTCHASECRET}/g" testnet.env
    - sed -i "s/CAPTCHACLIENT/${CAPTCHACLIENT}/g" testnet.env
    - cd -

.before_script_template: &testnet_webapp_vars
  before_script:
    - cd scripts
    - sed -i "12iIMAGE=$CONTAINER_REGISTRY" start.sh
    - cp template.env testnet.env
    - sed -i '19iDISABLE_INDEXER=true' testnet.env
    - sed -i "s/CORENODEIP/${TESTNET_CORENODE_IP2}/g" testnet.env
    - sed -i "s/WSPORT/49795/g" testnet.env
    - sed -i "s/HTTPPORT/49796/g" testnet.env
    - sed -i "s/CHAINID/49797/g" testnet.env
    - sed -i "s|SECRETKEYBASE|${TESTNET_SECRET_KEY_BASE}|g" testnet.env
    - sed -i "s/DBUSERNAME/${TESTNET_DB_USERNAME}/g" testnet.env
    - sed -i "s|DBPASSWORD|${TESTNET_DB_PASSWORD}|g" testnet.env
    - sed -i "s/DBNAME/${TESTNET_DB_NAME}/g" testnet.env
    - sed -i "s/DBHOST/${TESTNET_DB_HOSTNAME}/g" testnet.env
    - sed -i "s/REWARDS_CONTRACT/\#REWARDS_CONTRACT/g" testnet.env
    #- sed -i "s/REWARDCONTRACT/${TESTNET_REWARDCONTRACT}/g" testnet.env
    - sed -i "s/EXPLORERHOST/${TESTNET_SERVER_HOST}/g" testnet.env
    - sed -i "s/CAPTCHASECRET/${CAPTCHASECRET}/g" testnet.env
    - sed -i "s/CAPTCHACLIENT/${CAPTCHACLIENT}/g" testnet.env
    - cd -

.before_script_template: &mainnet_indexer_vars
  before_script:
    - cd scripts
    - sed -i "12iIMAGE=$CONTAINER_REGISTRY" start.sh
    - cp template.env mainnet.env
    - sed -i "s/Testnet/Mainnet/g" mainnet.env
    - sed -i "s/testnet.json/mainnet.json/g" mainnet.env
    - sed -i "s/CORENODEIP/${MAINNET_CORENODE_IP1}/g" mainnet.env
    - sed -i "s/WSPORT/39795/g" mainnet.env
    - sed -i "s/HTTPPORT/39796/g" mainnet.env
    - sed -i "s/CHAINID/39797/g" mainnet.env
    - sed -i "s|SECRETKEYBASE|${MAINNET_SECRET_KEY_BASE}|g" mainnet.env
    - sed -i "s/DBUSERNAME/${MAINNET_DB_USERNAME}/g" mainnet.env
    - sed -i "s|DBPASSWORD|${MAINNET_DB_PASSWORD}|g" mainnet.env
    - sed -i "s/DBNAME/${MAINNET_DB_NAME}/g" mainnet.env
    - sed -i "s/DBHOST/${MAINNET_DB_HOSTNAME}/g" mainnet.env
    - sed -i "s/REWARDCONTRACT/${MAINNET_REWARDCONTRACT}/g" mainnet.env
    - sed -i "s/EXPLORERHOST/${MAINNET_SERVER_HOST}/g" mainnet.env
    - sed -i "s/CAPTCHASECRET/${CAPTCHASECRET}/g" mainnet.env
    - sed -i "s/CAPTCHACLIENT/${CAPTCHACLIENT}/g" mainnet.env
    - cd -

.before_script_template: &mainnet_webapp_vars
  before_script:
    - cd scripts
    - sed -i "12iIMAGE=$CONTAINER_REGISTRY" start.sh
    - cp template.env mainnet.env
    - sed -i '19iDISABLE_INDEXER=true' mainnet.env
    - sed -i "s/Testnet/Mainnet/g" mainnet.env
    - sed -i "s/testnet.json/mainnet.json/g" mainnet.env
    - sed -i "s/CORENODEIP/${MAINNET_CORENODE_IP2}/g" mainnet.env
    - sed -i "s/WSPORT/39795/g" mainnet.env
    - sed -i "s/HTTPPORT/39796/g" mainnet.env
    - sed -i "s/CHAINID/39797/g" mainnet.env
    - sed -i "s|SECRETKEYBASE|${MAINNET_SECRET_KEY_BASE}|g" mainnet.env
    - sed -i "s/DBUSERNAME/${MAINNET_DB_USERNAME}/g" mainnet.env
    - sed -i "s|DBPASSWORD|${MAINNET_DB_PASSWORD}|g" mainnet.env
    - sed -i "s/DBNAME/${MAINNET_DB_NAME}/g" mainnet.env
    - sed -i "s/DBHOST/${MAINNET_DB_HOSTNAME}/g" mainnet.env
    - sed -i "s/REWARDCONTRACT/${MAINNET_REWARDCONTRACT}/g" mainnet.env
    - sed -i "s/EXPLORERHOST/${MAINNET_SERVER_HOST}/g" mainnet.env
    - sed -i "s/CAPTCHASECRET/${CAPTCHASECRET}/g" mainnet.env
    - sed -i "s/CAPTCHACLIENT/${CAPTCHACLIENT}/g" mainnet.env
    - cd -

build-image:
  stage: build
  tags:
    - docker_runner
  script:
    - cd scripts
    - aws ecr create-repository --repository-name $APP1_NAME || true
    - docker build --cache-from $TAG1_LATEST -f ./Dockerfile_webapp -t $TAG1_COMMIT -t $TAG1_LATEST ../
    - docker push $TAG1_COMMIT
    - docker push $TAG1_LATEST
    - docker build --cache-from $TAG2_LATEST -f ./Dockerfile_indexer -t $TAG2_COMMIT -t $TAG2_LATEST ../
    - docker push $TAG2_COMMIT
    - docker push $TAG2_LATEST
  only:
    <<: *sbx_triggers

sbx-schema:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-sbx-schema
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $SBX_SERVER_IP"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'sudo su - && export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - echo "RE_CAPTCHA_SECRET_KEY=${CAPTCHASECRET}" >> ./scripts/develop.env
    - echo "RE_CAPTCHA_CLIENT_KEY=${CAPTCHACLIENT}" >> ./scripts/develop.env
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$SBX_SERVER_IP:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker container rm -f $SCHEMA_NAME || true"
    - echo "Create DB schema"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "cd $APP_DIR/scripts && ./start.sh -e develop -r schema_aws -i $CONTAINER_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "cd $APP_DIR/scripts && ./token_remove.sh develop"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "cd $APP_DIR/scripts && ./token_rename.sh develop"
  only:
    <<: *sbx_triggers

deploy-sbx:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-sbx
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $SBX_SERVER_IP"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - echo "RE_CAPTCHA_SECRET_KEY=${CAPTCHASECRET}" >> ./scripts/develop.env
    - echo "RE_CAPTCHA_CLIENT_KEY=${CAPTCHACLIENT}" >> ./scripts/develop.env
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$SBX_SERVER_IP:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker container rm -f $APP2_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "cd $APP_DIR/scripts && ./start.sh -e develop -r run_indexer -i $CONTAINER_REGISTRY"
  only:
    <<: *sbx_triggers

tnet-schema:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-testnet-schema
  <<: *testnet_indexer_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $TESTNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 'sudo su - && export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$TESTNET_SERVER_IP1:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "docker container rm -f $SCHEMA_NAME || true"
    - echo "Create DB schema"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "cd $APP_DIR/scripts && ./start.sh -e testnet -r schema_aws -i $CONTAINER_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "cd $APP_DIR/scripts && ./token_remove.sh testnet"
  only:
    <<: *testnet_triggers

tnet-idxr:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-testnet-indexer
  <<: *testnet_indexer_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $TESTNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$TESTNET_SERVER_IP1:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "docker container rm -f $APP2_NAME || true"
    - echo "Start Indexer on $TESTNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP1 "cd $APP_DIR/scripts && ./start.sh -e testnet -r run_indexer -i $CONTAINER_REGISTRY"
  only:
    <<: *testnet_triggers

tnet-web1:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-testnet-webapp
  <<: *testnet_webapp_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $TESTNET_SERVER_IP2"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP2 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP2 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$TESTNET_SERVER_IP2:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP2 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP2 "docker container rm -f $APP1_NAME || true"
    - echo "Start webapp on $TESTNET_SERVER_IP2"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$TESTNET_SERVER_IP2 "cd $APP_DIR/scripts && ./start.sh -e testnet -r run_webapp -i $CONTAINER_REGISTRY"
  only:
    <<: *testnet_triggers

mnet-schema:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-mainnet-schema
  <<: *mainnet_indexer_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $MAINNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 'sudo su - && export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$MAINNET_SERVER_IP1:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "docker container rm -f $SCHEMA_NAME || true"
    - echo "Create DB schema"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "cd $APP_DIR/scripts && ./start.sh -e mainnet -r schema_aws -i $CONTAINER_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "cd $APP_DIR/scripts && ./token_remove.sh mainnet"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "cd $APP_DIR/scripts && ./token_rename.sh mainnet"
  only:
    <<: *mainnet_triggers

mnet-idxr:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-mainnet-indexer
  <<: *mainnet_indexer_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $MAINNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$MAINNET_SERVER_IP1:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "docker container rm -f $APP2_NAME || true"
    - echo "Start Indexer on $MAINNET_SERVER_IP1"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP1 "cd $APP_DIR/scripts && ./start.sh -e mainnet -r run_indexer -i $CONTAINER_REGISTRY"
  only:
    <<: *mainnet_triggers

mnet-web1:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-mainnet-webapp
  <<: *mainnet_webapp_vars
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - echo "Deploy to $MAINNET_SERVER_IP2"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP2 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP2 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$MAINNET_SERVER_IP2:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP2 "docker pull $TAG1_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP2 "docker container rm -f $APP1_NAME || true"
    - echo "Start webapp on $MAINNET_SERVER_IP2"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$MAINNET_SERVER_IP2 "cd $APP_DIR/scripts && ./start.sh -e mainnet -r run_webapp -i $CONTAINER_REGISTRY"
  only:
    <<: *mainnet_triggers
