variables:
  CONTAINER_REGISTRY: 769325152790.dkr.ecr.us-west-2.amazonaws.com
  AWS_REGION: us-west-2
  SBX_SERVER_IP: 172.31.77.59
  SERVER_USER: ubuntu
  SERVER_HOST: explorer.develop.energi.network
  APP_DIR: /home/$SERVER_USER
  APP1_NAME: explorer_indexer
  APP2_NAME: explorer_webapp
  TAG1_LATEST: $CONTAINER_REGISTRY/$APP1_NAME:latest
  TAG1_COMMIT: $CONTAINER_REGISTRY/$APP1_NAME:$CI_COMMIT_SHORT_SHA
  TAG2_LATEST: $CONTAINER_REGISTRY/$APP2_NAME:latest
  TAG2_COMMIT: $CONTAINER_REGISTRY/$APP2_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy-sbx

.sbx_triggers: &sbx_triggers
  refs:
    - sandbox

.runner:
  tags: [docker_runner]

build-webapp:
  stage: build
  tags:
    - docker_runner
  script:
    - cd scripts
    - aws ecr create-repository --repository-name $APP2_NAME || true
    - docker build --cache-from $TAG2_LATEST -f ./Dockerfile_webapp -t $TAG2_COMMIT -t $TAG2_LATEST ../
    - docker push $TAG2_COMMIT
    - docker push $TAG2_LATEST
  only:
    <<: *sbx_triggers

deploy-sbx:
  image: alpine:latest
  services:
    - docker:dind
  stage: deploy-sbx
  tags:
    - docker_runner
  script:
    - apk add --no-cache git curl build-base autoconf automake linux-headers openssl-dev openssh bash
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "aws ecr create-repository --repository-name $APP2_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "aws ecr get-login-password | docker login --username AWS --password-stdin $CONTAINER_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'export AWS_REGION=$AWS_REGION'
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP 'if [[ -d $APP_DIR/scripts ]]; then rm -rf $APP_DIR/scripts; fi'
    - scp -i $ID_RSA -o StrictHostKeyChecking=no -r ./scripts $SERVER_USER@$SBX_SERVER_IP:$APP_DIR/.
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "if [[ ! -d $APP_DIR/logs ]]; then mkdir $APP_DIR/logs; chmod 777 $APP_DIR/logs; fi"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker pull $TAG2_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "docker container rm -f $APP2_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SBX_SERVER_IP "cd $APP_DIR/scripts && ./start_sandbox.sh run_webapp"
  only:
    <<: *sbx_triggers
