apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret-db
type: Opaque
stringData:
  PGHOST: {{ .Values.envDataBaseSecrets.PGHOST | quote }} 
  PGPORT: {{ .Values.envDataBaseSecrets.PGPORT  | quote }} 
  PGDATABASE: {{ .Values.envDataBaseSecrets.PGDATABASE | quote }} 
  PGUSER: {{ .Values.envDataBaseSecrets.PGUSER  | quote }} 
  PGPASSWORD: {{ .Values.envDataBaseSecrets.PGPASSWORD  | quote }} 
  DATABASE_URL: {{ .Values.envDataBaseSecrets.DATABASE_URL  | quote }} 
