apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-web
#  labels:
#    app: explorer
#    component: explorer-webapp
spec:
  selector:
    app: explorer
    component: explorer-webapp
  clusterIP: None
  ports:
  - name: http
    port: 4000
