apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret-global
type: Opaque
stringData:
  ENERGISWAP_AUTH_SECRET: {{ .Values.envGlobalSecrets.ENERGISWAP_AUTH_SECRET | quote }} 
  WNRG_TOKEN_ADDRESS: {{ .Values.envGlobalSecrets.WNRG_TOKEN_ADDRESS | quote }} 
  SECRET_KEY_BASE: {{ .Values.envGlobalSecrets.SECRET_KEY_BASE  | quote }} 
  REWARDS_CONTRACT: {{ .Values.envGlobalSecrets.REWARDS_CONTRACT | quote }}
