apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid # Do not run concurrently!
  schedule: '*/3 * * * *'     # Run every 3 minutes 
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-indexer # Run under the service account created above
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl # Specify the kubectl image
              command: # The kubectl command to execute
                - /bin/sh
                - -c
                - |
                  SCRIPT_ADDR=scripts/token_remove.sh
                  FILTER_INDEXER_POD=$(kubectl get pods -l component=explorer-indexer --field-selector=status.phase==Running --no-headers -o custom-columns=":metadata.name")
                  kubectl exec -it $FILTER_INDEXER_POD -- sh $SCRIPT_ADDR {{ .Values.cronjob.env }}
