apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret-captcha
type: Opaque
stringData:
  RE_CAPTCHA_SECRET_KEY: {{ .Values.envCaptchaSecrets.RE_CAPTCHA_SECRET_KEY  | quote }} 
  RE_CAPTCHA_CLIENT_KEY: {{ .Values.envCaptchaSecrets.RE_CAPTCHA_CLIENT_KEY  | quote }}
