FROM bitwalker/alpine-elixir-phoenix:1.14

RUN apk update
RUN apk upgrade
RUN apk --no-cache --update add alpine-sdk make gcc gmp-dev automake libtool inotify-tools autoconf python3 file openjdk11

# Get Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ARG MIX_ENV=prod
ENV PATH="$HOME/.cargo/bin:/opt/mix:/usr/lib/jvm/java-11-openjdk/bin${PATH}"
ENV RUSTFLAGS="-C target-feature=-crt-static"
ENV LDFLAGS="-L/opt/app/_build/$MIX_ENV/lib -L/usr/local/lib -L/usr/local/lib/elixir/lib -L/usr/local/lib/erlang -L/usr/lib \
    -I/usr/local/include -I/usr/include -I/usr/lib/erlang/lib/eldap-1.2.9/include ${LDFLAGS}"
ENV LD_LIBRARY_PATH="/opt/app/_build/$MIX_ENV/lib:/usr/local/lib:/usr/local/lib/elixir/lib:/usr/local/lib/erlang:/usr/lib:$LD_LIBRARY_PATH"
ENV LIBPATH="$LD_LIBRARY_PATH"

ENV PORT=4000

ARG SECRET_KEY_BASE=IWTVkfnfrKBta0U6p4UUbajb44wu5lYcrK0B6drT+dvnuTvSN18vliy3cxUnLXt3

# wobserver interface
ARG WOBSERVER_ENABLED=false

# Enable both Indexer and Webapp
ENV DISABLE_INDEXER=false
ENV DISABLE_WEBAPP=true

#
ARG BLOCKSCOUT_PROTOCOL=https
ARG BLOCK_TRANSFORMER=base
#ARG GAS_PRICE=11
ARG ETHEREUM_JSONRPC_TRANSPORT=http
ARG COIN=NRG
ARG ENABLE_TXS_STATS=true
ARG SHOW_TXS_CHART=true
ARG ALLOWED_EVM_VERSIONS=petersburg
ARG ETHEREUM_JSONRPC_VARIANT=geth
ARG COINGECKO_COIN_ID=energi
ARG EMISSION_FORMAT=MNRG
ARG MAX_SKIPPING_DISTANCE=2
ARG CHECK_ORIGIN=true

# Energi
ARG LOGO=/images/EnergiLogoLight.png
ARG LOGO_FOOTER=/images/EnergiLogoLight.png
ARG RELEASE_LINK=https://github.com/energicryptocurrency/energi3-blockscout

# Cache elixir deps
ADD mix.exs mix.lock ./
ADD apps/block_scout_web/mix.exs ./apps/block_scout_web/
ADD apps/explorer/mix.exs ./apps/explorer/
ADD apps/ethereum_jsonrpc/mix.exs ./apps/ethereum_jsonrpc/
ADD apps/indexer/mix.exs ./apps/indexer/

ADD . .

# create directory
RUN if [[ ! -d apps/block_scout_web/priv/static ]]; then mkdir -p apps/block_scout_web/priv/static; fi
RUN if [[ ! -d apps/ethereum_jsonrpc/priv/static ]]; then mkdir -p apps/ethereum_jsonrpc/priv/static; fi
RUN if [[ ! -d apps/explorer/priv/static ]]; then mkdir -p apps/explorer/priv/static; fi
RUN if [[ ! -d apps/indexer/priv/static ]]; then mkdir -p apps/indexer/priv/static; fi

# Build deps
RUN mix local.hex --force && echo "hex installed"
RUN mix local.rebar --force && echo "rebar installed"

# Get dependencies
RUN mix deps.get

RUN apk add --update nodejs npm

# Add rebar3.config
RUN pwd
#RUN mv scripts/rebar3.config deps/libsecp256k1/.
#RUN cd deps/libsecp256k1 && ln -s rebar3.config rebar.config && rebar compile && cd -

# Compile dependencies
RUN mix deps.compile
RUN echo "deps installed"

# Build app
RUN mix compile && npm install npm@latest
RUN echo "app installed"

# Remove dev packages
RUN apk update && apk del --force-broken-world alpine-sdk make gcc gmp-dev automake libtool inotify-tools autoconf python3
RUN rm -rf /opt/hex
RUN rm -rf /var/cache/apk/*

# Start app
RUN mix phx.digest
